folder_path: "/Users/saynepark/Downloads/Kontext (10)"
page_title: 'The Illusion of Fairness: A Reflection on Squid Game and Korean Society'
author: Hwang Dong-hyuk
publish_date: "9/7/2021"
thumbnail_alt: "old korea town"
#banner_alt: "Image of the Crow's Eye View"