folder_path: C:\Users\advai\Downloads\DayInTheLife\
page_title: A Day in the Life of Novelist Gubo
author: Park Taewon
publish_date: "12/7/1938"
thumbnail_alt: "Image of the Book Cover"
banner_alt: "Image of the Book Cover"