folder_path: C:\Users\advai\Downloads\Reflection
page_title: Reflection of History and Society in Korean Literature
author: Team Kontext
publish_date: "27/03/2025"
tags:
  - "research"
  - "history"
  - "advice"