folder_path: /Users/saynepark/Downloads/Kontext (3)
page_title: Lost in the Crowd - The Isolation of Modern Gyeongseong
author: Pak Taewon
publish_date: 7/12/1938
thumbnail_alt: Image of Seoul Station Gyeongui-Jungang Line terminal
banner_alt: image of a teahouse from the drama Yi Sang, Beyond Yi Sang