folder_path: /Users/saynepark/Downloads/Kontext (2)
page_title: Wanderings Gubo - A Portrait of Gyeongseong Lost Youth
author: Pak Taewon
publish_date: 7/12/1938
thumbnail_alt: Image of old Korea's Currency Museum building.
banner_alt: Image of an main character of the book. 