folder_path: /Users/saynepark/Downloads/Kontext (6)
page_title: Walking Through 1930s Korea with A Day in the Life of Kubo the Novelist
author: Pak Taewon
publish_date: 7/12/1938
thumbnail_alt: Image of the Mitsukoshi Department Store Main Branch
banner_alt: image of the Mitsukoshi Department Store Main Branch