folder_path: /Users/saynepark/Downloads/Kontext (1)
page_title: Walking Through 1930s Korea with A Day in the Life of Kubo the Novelist
author: Pak Taewon
publish_date: 7/12/1938
thumbnail_alt: Image of old Korea's Currency Museum building.
banner_alt: Image of an main character of the book. 