folder_path: C:\Users\advai\Downloads\Hex
page_title: 'Infinite Hexahedron of Architecture - Literature Through the Lens of Physics'
author: Yi Sang
publish_date: "7/1932"
thumbnail_alt: "Image of the Mitsukoshi Department Store Main Branch"
banner_alt: "Image of the Mitsukoshi Department Store Main Branch"