folder_path: /Users/saynepark/Downloads/Kontext (4)
page_title: Korean Phonology and Foreign Word Transcription
author: Korean Bible Society (KBS)
publish_date: 1998
thumbnail_alt: Image of old korean book
banner_alt: image of a old korean book