folder_path: /Users/saynepark/Downloads/Kontext (7)
page_title: Avant-Garde Poetics- Lee Sang and Experimental Notation in Korean and Japanese Poetry
author: Yi Sang
publish_date: 7/24/1934
thumbnail_alt: Image of the Crow's Eye View
banner_alt: image of the Crow's Eye View