folder_path: /Users/saynepark/Downloads/제목 없는 문서
page_title: Literature as Resistance- Han Kang, Human Acts, and the Struggle Against Historical Erasure
author: Han Kang
publish_date: 5/19/2014
thumbnail_alt: Image of the old Korea
banner_alt: image of the old Korea