folder_path: /Users/saynepark/Downloads/Kontext
page_title: Book 3
author: Han Trio
publish_date: 13/10/2012
thumbnail_alt: Image of old korean books with yellowed pages.
banner_alt: Image of an open book on a table